version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Environment variables
      - env
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD;
      - docker build -t $APP_IMAGE_NAME:$IMAGE_TAG -f Dockerfile.ecs .
      - docker tag $APP_IMAGE_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_IMAGE_NAME:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $APP_IMAGE_NAME $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $APP_IMAGE_NAME $IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_IMAGE_NAME:$IMAGE_TAG
artifacts:
  files:
    - imagedefinitions.json
